<?php

namespace AppBundle\Repository;

/**
 * EmmisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmmisionRepository extends \Doctrine\ORM\EntityRepository
{
}
