<?php

namespace AppBundle\Repository;

/**
 * ShortCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShortCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
